### ISSUE TITLE
valid tailwind syntax, but `twust` returns compile error

### ISSUE THREAD

**Issue by JustSimplyKyle** [Oyelowo/twust#13]
- `group-data-[selected=Right]:w-[30px]` 
- `group-aria-[main-page=false]/main:hidden` / `group-data-[main-page=false]/main:hidden`
- `*:overflow-scroll`

All of these produce valid tailwind css
```css
.group\/main[data-main-page=false] .group-data-\[main-page\=false\]\/main\:hidden {
  display: none;
}

.group[data-selected=Right] .group-data-\[selected\=Right\]\:w-\[30px\] {
  width: 30px;
}

.\*\:overflow-scroll > * {
  overflow: scroll;
}
```
